Fdp35 my posts
JosephOri/StoicReads pull request #23
Opened 2024-07-27 15:43 UTC by TomerMiz10

## Task link from JIRA:
https://mssplinter10-1711638164183.atlassian.net/jira/software/projects/FDP/boards/1?selectedIssue=FDP-35

## Description:
- Refactor: `EditProfilePage` to remove userName field, Remove console log statements (2acad4b)
- feat: Add toggle button to show all/my posts in HomePage (b3670ad)
- Feat: Add `getPostsByUser` function {description} API endpoint. And toggle button to show all\my posts in `HomePage`. (b088044)
- Refactor: Remove unnecessary imports from `EditProfilePage.tsx` . (02c4048)
- Refactor `EditProfilePage` component to improve code readability and maintainability (ccc5ef8)
- chore: Refactor `EditProfilePage` component to improve code readability and maintainability (3707d73)
- Merge PR #22 from branch 'master' of https://github.com/nitzanto/Foodies-WebApp into `FDP35-my-posts` (c82043a)
- chore: Update `selectedPost` comments handling in `HomePage.tsx` (c2f67ed)
- feat: Add `Book`, `Comment`, `Post`, and `Review` interfaces to frontend. (7453265)
- feat: Add `_id` attribute to `Post` and `Review` interfaces for creating posts. (07f5dfc)

## Code Owners:
@TomerMiz10 

### Summary
Display MyPosts in HomePage.
Edit profile details refinements.

2024-07-27 15:46 UTC, TomerMiz10 commented on frontend/src/pages/ProfilePage/EditProfilePage.tsx
i fixed indentations here, and deleted `Grid` of `username`

2024-07-27 15:57 UTC, nitzanto requested changes

2024-07-27 15:57 UTC, nitzanto commented on backend/src/controllers/auth.controller.ts
Delete console logs

2024-07-27 15:57 UTC, nitzanto commented on backend/src/interfaces/Post.ts
Why was this file re-created?

2024-07-27 15:57 UTC, nitzanto commented on backend/src/interfaces/Review.ts
Why _id was added? this shouldnt be changed

2024-07-27 16:19 UTC, TomerMiz10 commented on backend/src/controllers/auth.controller.ts
done

2024-07-27 16:21 UTC, TomerMiz10 commented on backend/src/interfaces/Review.ts
done

2024-07-27 16:33 UTC, nitzanto requested changes

2024-07-27 16:33 UTC, nitzanto commented on backend/src/interfaces/Review.ts
> +
delete this mongoose from this file

2024-07-28 19:26 UTC, nitzanto submitted a review, later dismissed

2024-07-28 19:26 UTC, nitzanto commented on backend/src/interfaces/Post.ts
Why did you add this?

2024-07-29 15:56 UTC, omrifinegold111 approved these changes

2024-07-29 15:57 UTC, omrifinegold111 approved these changes
nice

2024-07-29 17:34 UTC, merged